### PR TITLE
Ability to import def pfr data

### PR DESCRIPTION
**Pull request by felixblochwitz**
This PR addresses issue https://github.com/nflverse/nfl_data_py/issues/108

It adds the option to specify `s_type` as `def` for the functions `import_seasonal_pfr` and `import_weekly_pfr` by adding them as valid inputs to the function `_validate_pfr_inputs`.

Data for defensive stats is available since 2018 (same starting point as other categories) here: https://github.com/nflverse/nflverse-data/releases/tag/pfr_advstats. Thus, loading this data should work as intended.

### CODE REVIEW

**Review by alecglen — APPROVED** [review]
Looks good, thanks @felixblochwitz!

**Comment by alecglen** [comment]
I changed the PR's base branch from `main` to `v0.3.3` so it will merge in with the next package version being released this week. If you merge that branch's commits into your branch, then the test suite should pass and we'll get this merged.

**Comment by felixblochwitz** [comment]
> I changed the PR's base branch from `main` to `v0.3.3` so it will merge in with the next package version being released this week. If you merge that branch's commits into your branch, then the test suite should pass and we'll get this merged.

Thanks for your comment. I think I merged the commits from the `v0.3.3` branch successfully into my branch (hope I did this correctly, it's my first time contributing to something public). If you need me to do anything else, just let me know.

**Comment by alecglen** [comment]
Perfect - thanks again! 👍

**Pull request merged**
